web:
  image: kevincoyle/drupal8
  volumes:
    - "./modules:/app/modules"
    - "./themes:/app/themes"
    - "./config:/app/sites/default/config"
  ports:
    - "8082:80"
  environment:
    - ALLOW_OVERRIDE=true
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal8
